# Generated by Django 4.1 on 2022-11-07 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
